site_name: "LLMCode Docs"

theme:
  name: material
  logo: assets/book_logo.png
  favicon: assets/book_logo.png

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            docstring_style: google
            show_root_heading: true
            show_source: true
            separate_signature: true
            line_length: 80
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_inheritance_diagram: true

nav:
  - Home: index.md

  - Installation: installation.md
  - Usage: usage.md
  - Customization: customization.md

  - Reference:
      - Entrypoint: reference/entrypoint.md
      - Utils:
          - Auxiliary: reference/utils/auxiliary.md
          - Completion: reference/utils/completion.md
          - Document: reference/utils/document.md
          - File_utils: reference/utils/file_utils.md
          - Logger: reference/utils/logger.md
