name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main # Trigger workflow on push to the main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocstrings[python] mkdocs-autorefs mkdocs-material mkdocs-gen-files

      - name: Generate API Reference Documentation
        run: |
          python docs/scripts/gen_ref_pages.py
          echo "Generated reference documentation."

      - name: Build MkDocs site
        run: mkdocs build # Generates the static site in the ./site folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./site
